# Generated by Django 3.2.4 on 2021-09-16 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('cc', models.CharField(max_length=150)),
                ('year', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('4Wheel', '4Wheel'), ('Electric', 'Electric'), ('Pick-up', 'Pick-up'), ('Vans', 'Vans')], default='Sedan', max_length=150)),
                ('color', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=150)),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('CVT', 'CVT')], default='Manual', max_length=150)),
                ('passenger', models.CharField(choices=[('2', '2'), ('4', '4'), ('5', '5'), ('7', '7'), ('15', '15')], default='2', max_length=150)),
                ('bootCapacity', models.CharField(max_length=150)),
                ('carFuel', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], default='Petrol', max_length=150)),
                ('availability', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=150)),
                ('features', multiselectfield.db.fields.MultiSelectField(choices=[('Sunroof', 'Sunroof'), ('GPS', 'GPS'), ('All Wheel drive', 'All Wheel drive'), ('Heated seats', 'Heated seats'), ('Bluetooth', 'Bluetooth'), ('Apple CarPlay/Android Auto', 'Apple CarPlay/Android Auto'), ('Backup camera', 'Backup camera'), ('Cruise Control', 'Cruise Control'), ('Push-Button Start', 'Push-Button Start')], max_length=150)),
                ('image', models.ImageField(upload_to='services/images')),
                ('addedDate', models.DateField()),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
