# Generated by Django 3.2.4 on 2021-09-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleinfo',
            name='user_info',
        ),
    ]
