# Generated by Django 3.2.4 on 2021-09-26 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0006_bookinstantly'),
    ]

    operations = [
        migrations.CreateModel(
            name='callBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('pickAddress', models.CharField(max_length=255)),
                ('pickDate', models.DateField()),
                ('pickTime', models.TimeField()),
                ('dropAddress', models.CharField(max_length=255)),
                ('dropDate', models.DateField()),
                ('dropTime', models.TimeField()),
                ('status', models.CharField(choices=[('Not Called', 'Not Called'), ('Called', 'Called')], default='Processing', max_length=150)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.vehicleinfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
