# Generated by Django 3.2.4 on 2021-09-27 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='car_id',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='user_id',
            new_name='user',
        ),
    ]
