# Generated by Django 3.2.4 on 2021-09-27 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20210927_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='book',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='car',
            new_name='car_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='user_id',
        ),
    ]
