# Generated by Django 3.2.4 on 2021-09-27 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20210927_1130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
    ]
